version: '3'

services:

  proxy:
    image: nginx:1.13
    container_name: nginx1
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro


  web: # proxy_pass  http://web;    esse nome vai no nginx.config.
    image: httpd  # this will use httpd:latest
    container_name: apache-http-server
