version: '3'

services:
  nginx-1: # pode ser qualquer nome
    image: nginx
    container_name: nginx1
    ports:
      - 8080:80
    volumes:
      - ./html:/usr/share/nginx/html


# docker-compose up -d
# docker-compose down
# docker container exec -it nginx1 bash

# http://localhost:8080
# http://localhost:8080/exemplo/index.html
# http://localhost:8080/exemplo/       precisa da barra